### ISSUE TITLE
Example File Not Running as Described in the ReadMe

### ISSUE THREAD

**Issue by adityatb** [kosta-pmf/dnn-audio-watermarking#2]
Hi there,

Excited to try this repo! I was trying to get this to run and found that there's seems to be some inconsistency with the pretrained model and it's expected input shape.

I tried to `librosa.load(audio_file, target_sr=16000)` and then run the `main.embed()` on it as described in the ReadMe and I get an error with Tensor Shapes not matching.

Perhaps I'm missing some extra steps to get you there. Appreciate any help you can offer!

Cheers!

I should clarify - I'm running it with the example files provided. There also seems to be a mismatch for the message shapes -> I get (1, 512) vs (16, 2, 512)

**Comment by kosta-pmf** [comment]
Hello,
Thanks for the issue. We somehow missed it until now. We will look into it.

**Comment by AAA-eng-alt** [comment]
> 你好呀，
> 
> 很高兴尝试这个回购！我试图让它运行，发现似乎与预训练模型和预期的输入形状有些不一致。
> 
> 我尝试`librosa.load(audio_file, target_sr=16000)`然后`main.embed()`按照自述文件中的描述在其上运行，但出现张量形状不匹配的错误。
> 
> 也许我错过了一些额外的步骤来让你到达那里。感谢您提供的任何帮助！
> 
> 干杯!
> 
> 我应该澄清一下 - 我正在使用提供的示例文件运行它。消息形状似乎也不匹配 -> 我得到 (1, 512) vs (16, 2, 512)

**Comment by AAA-eng-alt** [comment]
Happy to answer your question, I ran into a similar tensor mismatch when testing. What you have here is the problem of SFTF and BATCH_SIZE. You try to change the HOP_Length parameter in the config.py file, reduce the frame spacing, to match the amplitude spectrum of 64 width, try it, mine has worked.

**Comment by my-yy** [comment]
same issue

**Comment by slavzilla** [comment]
@my-yy please refer to @AAA-eng-alt comment, it is the answer to your issue.
