### ISSUE TITLE
Useless, DO WASTE YOUR TIME WITH THIS CODE

### ISSUE THREAD

**Issue by amgomez** [kosta-pmf/dnn-audio-watermarking#9]
I have spent a day and a half patching this code and trying to make it work. It is completely BS, do not waste your time.

First you will get an "transpose expects a vector of size 2. But input(1) is a vector of size 3" that you can solve by simulating a batch of one dimension: watermarked_signal = embed(embedder, [audio])

But then you will discover the DNN input is fixed to 64 frames, any different size will lead to an error. 

You can try and fix the size of your audio file to 65*512 samples to achieve this number of frames.

BUT THEN you will have an error with the tensor dimensions of the message to be encoded (which is randomly selected from file message_pool.npy which, by the way, it is on samples directory and not in the one specified in config.py, you will also have to fix that). The way a message is expected, with shape=(None, 16, 2, 512), completely differs from that included (by the authors) in message_pool.npy (1, 512). There is no indication on how the message must be constructed to achieve the required shape. 

DO NOT WASTE YOUR TIME IN THIS CODE.

Now, it's clear to me that authors just wanted to get their paper accepted...

**Comment by kosta-pmf** [comment]
Not true. Not a very nice comment. We tried to merge the code of our previous publication with the following one in order to keep building upon this repo. That process did not go as planned and some inconsistencies occurred. We instructed everyone who was kind enough to ask to revert to the verified version of the code. After that, we did not get any complaints. Now, we reverted it ourselves. Also, this code is a work in progress. Not yet a production-ready software. Its main purpose was indeed to be used by reviewers to check its validity. But, you could have phrased it more nicely, and been a better person.

**Comment by XuandongZhao** [comment]
@kosta-pmf, I'm facing the same issues that @amgomez described. Could you please share a solution that works with the code?

**Comment by mayank-git-hub** [comment]
@kosta-pmf I agree that it is not a nice comment, but I can totally understand where it is coming from. It doesn't require much time for someone well-versed in this repository to make it workable, but for a person seeing the code for the first time it can be very frustrating.

@XuandongZhao, I have spent some time and made it workable at this fork: https://github.com/mayank-git-hub/dnn-audio-watermarking-debugged/tree/main

Let me know if it works for you. You may need to make some modifications to the signal loading part of run.ipynb
EDIT: I have added a sample.wav to the repo for demo

**Comment by mayank-git-hub** [comment]
Also, I tried to make the code work on flexible length audio, but it seems that the decoder expects a fixed size input which makes it impossible to decode variable length inputs. Also, the output of the encoder does not match the input, which further complicates the process...

**Comment by kosta-ucg** [comment]
We have reverted the repository to a previous version which shouldn't cause problems but unfortunately does not work with variable-length inputs. This version is designed to handle 512x64x2 tensor input, as showcased in the 'embed' function in main.py.

We have not expected this repo to gain this much attention. It is gratifying, but also demanding.  We are actively working on developing an enhanced watermarking solution and will publish it hopefully in the near future. 

Thank you for your keen interest. We encourage you to craft your own watermarking algorithms using this framework or, even better, explore innovative approaches. We sincerely apologize for any inconvenience caused.
